fafasfasf

@startuml
class Foo
class Bar
Foo ..|> Bar
@enduml

@startuml
abstract        abstract2
class Foo {
    String data
}
class Bar
Bar <|-- Foo
Bar : int size()
abstract class  "abstract class"
annotation      annotation
circle          circle
()              circle_short_form
class           class
diamond         diamond
<>              diamond_short_form
entity          entity
enum            enum
interface       interface
@enduml


<sdfafasf
@enduml  
@startuml
fsdf
adfdsf
class FOo
FOo *--> 
@enduml
